### ISSUE TITLE
Add io.opentracing.contrib:opentracing-jaxrs2 to opentracing fraction

### ISSUE THREAD

**Issue by michbeck100** [thorntail/thorntail#1028]
Since the jaxrs fraction is default for the microprofile, the corresponding dependency for instrumenting jaxrs resources should be included as transitive dependency to org.wildfly.swarm:opentracing.

**Comment by kenfinnigan** [comment]
What does that dependency bring above MP OpenTracing?

**Comment by michbeck100** [comment]
It enables tracing instrumentation for JAX-RS endpoints. Just compare with io.opentracing.contrib:opentracing-spring-cloud-starter.  I think the opentracing fraction should auto configure the JAX-RS server and client tracing, too. Perspectively there should even be support for more components like spa or messaging.

**Comment by Ladicek** [comment]
Is this about Thorntail v2 or v4? Judging from references to "fractions", it's probably about v2, in which case this belongs to http://issues.jboss.org/browse/THORN. Also the `microprofile-opentracing` should be what you're after, as @kenfinnigan suggests. There was a bit of discussion about differences between `opentracing` and `microprofile-opentracing` here: https://github.com/thorntail/thorntail/pull/990

**Comment by michbeck100** [comment]
Didn't know of `microprofile-opentracing`, but thats exactly what this issue is about 😉. Maybe this could be backported to v2, but i will file an issue in the JIRA then.

**Comment by kenfinnigan** [comment]
@michbeck100 `microprofile-opentracing` also exists in v2

**Comment by michbeck100** [comment]
Thanks for the hint, seems that it was released with io.thorntail groupId. I was looking for org.wildfly.swarm.
