### ISSUE TITLE
Hibernate Search EntityManager wrapping should be typesafe

### ISSUE THREAD

**Issue by kg6zvp** [thorntail/thorntail#1036]
**Is your feature request related to a problem? Please describe.**
Tight coupling is introduced and compile-time safety is removed by the current method of wrapping `EntityManager` in `FullTextEntityManager`

**Describe the solution you'd like**
Introduce a mechanism for keeping the Hibernate Search code in the Hibernate Search module and out of the JPA Support module.

**Additional context**
The current code in the `opentracing` package might also benefit from a standard wrapping mechanism.

**Comment by kg6zvp** [comment]
Given that this issue is marked as `Done`, ok to close?

**Comment by kenfinnigan** [comment]
Not sure why I didn't do that earlier, sorry
