### ISSUE TITLE
MicroProfile LRA fraction

### ISSUE THREAD

**Issue by mmusgrov** [thorntail/thorntail#1040]
The [Eclipse MP LRA](https://github.com/eclipse/microprofile-lra) project is adding a Saga like feature to the MicroProfile collection of specifications. It would advantageous to have an implementation of that specification running on Thorntail.

The [narayana code base contains an implementation](https://github.com/jbosstm/narayana/tree/master/rts/lra) of the specification and the proposal is package that implementation as a Thorntail MicroProfile fraction.

I will be following up with another PR on the [Thorntail examples repo](https://github.com/thorntail/thorntail-examples) that will include two examples of how to use it.

**Comment by kenfinnigan** [comment]
The new approach is for all MP implementations to be part of https://github.com/smallrye/ where they can then be used by Thorntail or other implementations as they see fit.

It looks like the current Narayana based implementation heavily relies on prior WildFly Swarm code, so this would need to be refactored to be implementation independent for SmallRye

**Comment by mmusgrov** [comment]
@kenfinnigan Fair enough. Are there any guidelines on how to do the refactor?

**Comment by kenfinnigan** [comment]
Most of the team have done one or more refactors of the existing code, so you could message the Thorntail internal ML to ask if they have any thoughts
