### ISSUE TITLE
microprofile-openapi @Extension is missing in /openapi.yml model

### ISSUE THREAD

**Issue by dvddhln** [thorntail/thorntail#1044]
Hi,
I am currently trying to use @Extension annotation from the microprofile-openapi fraction. The example is @Extensions({@Extension(name = "x-audience", value = "internal")})

which I annotate on a GET resource method. However this custom extension is not populated in the yaml file when accessing the /openapi url. Is this a bug or is this currently not supported? Perhaps I am doing something wrong aswell, but in that case I'd appreciate any light on how to actually use it.

/david

**Comment by kenfinnigan** [comment]
Is this with v2 or v4?

Thoughts @EricWittmann?

**Comment by dvddhln** [comment]
I'm running 2.0.0.Final.

**Comment by kenfinnigan** [comment]
Ok, if this turns out to be a bug, it will need to be raised here: http://issues.jboss.org/browse/THORN

GitHub issues are for v4 only

**Comment by EricWittmann** [comment]
I'll try to look into this today, but it's likely a bug.

**Comment by EricWittmann** [comment]
Alright - so `@Extensions` on jax-rs methods are not being read.  At this point, this is really a bug in SmallRye and should probably be raised/tracked there.

https://github.com/smallrye/smallrye-open-api

**Comment by dvddhln** [comment]
Alright, thank you, will raise the issue there.

**Comment by kenfinnigan** [comment]
Thanks @dvddhln, will close this one
