### ISSUE TITLE
Jose fraction keystore uri path?

### ISSUE THREAD

**Issue by dvddhln** [thorntail/thorntail#1080]
Hi,
Would it be possible to support a URI path for the key store in the jose fraction? I am thinking it could be something similar as in the JWT fraction with the configuration jwks-uri where you point out a remote jwks.

BR 

David

**Comment by kenfinnigan** [comment]
Is this related to v2?

If so, please raise an issue here instead: http://issues.jboss.org/browse/THORN

**Comment by sberyozkin** [comment]
Hi David, for the JWK stores, signatures only, it should work, yes, similarly to the JWT fraction, It will require some thought. Ex, Jose4J HTTPS retrieval works over 'plain' HTTPS, no server certificates. It might also require supporting per-signature or per-encryption key stores, as opposed to the the 'shared' store right now, getting the private encryption keys over HTTPS would not be a usual thing to do. I'd expect in the short term at least the 'old' JKS will still prevail.
I'm thinking of opening a low priority issues to get few improvement ideas accumulated and then act on them, Ken, hope you are OK with it :-)

**Comment by kenfinnigan** [comment]
@sberyozkin as there are more pressing priorities right now, please just open some JIRAs and leave it there

**Comment by sberyozkin** [comment]
Yes, that was the plan, keep the record of the improvement ideas, thanks

**Comment by sberyozkin** [comment]
https://issues.jboss.org/browse/THORN-2135.

David, please keep new ideas coming :-), in due to time we will look closer and enhance as needed.

**Comment by kenfinnigan** [comment]
Closing in favor of new JIRA
