### ISSUE TITLE
bootstrap module shades dependencies

### ISSUE THREAD

**Issue by reitzmichnicht** [thorntail/thorntail#1124]
The io.thorntail:bootstrap module does include itself the both dependencies:
```
      <exclusions>
        <exclusion>
          <artifactId>jboss-modules</artifactId>
          <groupId>org.jboss.modules</groupId>
        </exclusion>
        <exclusion>
          <artifactId>snakeyaml</artifactId>
          <groupId>org.yaml</groupId>
        </exclusion>
      </exclusions>
```

As it also marks this as compile dependencies the classpath has now duplicate classes. Please stop shading dependencies.

Kind regards,
Michael

**Comment by kenfinnigan** [comment]
As this relates to v2, master branch, please raise an issue here: http://issues.jboss.org/browse/THORN

We'd also appreciate a PR to resolve it.
