### ISSUE TITLE
Introduction of editorconfig to assist in code styling

### ISSUE THREAD

**Issue by kg6zvp** [thorntail/thorntail#1129]
**Is your feature request related to a problem? Please describe.**
I usually indent my java projects with tabs, so I often have to fight my code editor when working on Thorntail in order to indent with spaces.

**Describe the solution you'd like**
I would like to introduce a `.editorconfig` file to the repository (See the site [here](https://editorconfig.org/)) in order to assist with code styling as it is supported in almost all major IDEs.

I personally have experience with editorconfig and have been using it locally to help me properly format files for PRs on this project already and it works very well in the editors I use most:
- NetBeans (via [this](https://github.com/welovecoding/editorconfig-netbeans) plugin)
- VS Code (via [this](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) plugin)

For a complete list of supported editors/IDEs, see their page on it [here](https://editorconfig.org/#download).

** Starter Template ** (based on what I've seen in the project)
```
root = true

[*]
insert_final_newline = true
trim_trailing_whitespace = true
charset = utf-8

[*.java]
indent_style = space
indent_size = 4
curly_bracket_next_line = false
spaces_around_operators = true
continuation_indent_size = 8
indent_brace_style = Java

[*.xml]
indent_style = space
indent_size = 2
indent_brace_style = K&R
```

**Comment by Ladicek** [comment]
This is a good idea IMHO.

**Comment by manovotn** [comment]
As long as we add a note to README about this (kind of "How to contribute" chapter?), it sounds like good idea.

**Comment by kg6zvp** [comment]
@kenfinnigan We should definitely continue to have a `How to Contribute`, but I believe we should also have an editorconfig file in addition. This helps by letting the editor work with the contributor instead of having to do a `sed 's/\t/    /g'` for every file they have opened before making a commit.

FYI, editorconfig files are supported out of the box on IntelliJ.

**Comment by Holi60k** [comment]
It works really well with IntelliJ IDEA, and Eclipse and other IDEs require some kind of plugin, but this thing is a game changer, no more "I forgot to setup my formatter" things! :D
