### ISSUE TITLE
NPE when using LoggingFraction.customFormatter() overload

### ISSUE THREAD

**Issue by michbeck100** [thorntail/thorntail#1154]
**Describe the bug**
The method overload of [LoggingFraction.customFormatter()](https://github.com/thorntail/thorntail/blob/0d5485967bae390825c4997393e9ac57bb995821/fractions/wildfly/logging/src/main/java/org/wildfly/swarm/logging/LoggingFraction.java#L199) will produce a NullPointerException.

**To Reproduce**
It's obvious when looking at the code.

**Expected behavior**
No exception ;-)

**Comment by Ladicek** [comment]
This belongs to JIRA: http://issues.jboss.org/browse/THORN But you're right, the NPE is indeed obvious :-)

**Comment by kenfinnigan** [comment]
Closing as it has a JIRA
