### ISSUE TITLE
Thorntail plugin is unable to run with Maven 3.6.0

### ISSUE THREAD

**Issue by dfahren** [thorntail/thorntail#1170]
When I build my projects with Maven 3.6.0 the Thorntail plugin 2.2.1 and 2.3.0.Final-SNAPSHOT spurts out lots of ERRORs. Please see below.

You can reproduce this error by building example project "Thorntail exampe: STM".

Expected is a flawless package phase of the Thorntail plugin.

I'm running Windows 7 Enterprise, Java 1.8.0_192, Maven 3.6.0, Git 2.19.1

Here you can find a stack trace:
https://gist.github.com/dfahren/9e4e48a6623c5c86fc75aba0e926d1cf

Regards,
Dietrich

**Comment by Ladicek** [comment]
This is Thorntail 2, so the issue belongs to JIRA. Turns out there's one for Maven 3.6 already: https://issues.jboss.org/browse/THORN-2229 -- suggest you follow that one.
