### ISSUE TITLE
JWT Login Module - Roles Provider

### ISSUE THREAD

**Issue by vepo** [thorntail/thorntail#1209]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a microservice dynamic roles provider. The roles will change according with profile configuration.

**Describe the solution you'd like**
When configure JWTLoginModule, I can implement a interface that given the JWT token, retrieves all user roles.

**Describe alternatives you've considered**
When configure JWTLoginModule, I can implement a interface that given the user group, retrieves all user roles.

**Additional context**
According with the [code](https://github.com/thorntail/thorntail/blob/master/fractions/microprofile/microprofile-jwt/src/main/java/org/wildfly/swarm/microprofile/jwtauth/deployment/auth/jaas/JWTLoginModule.java#L105) all roles mapping (group to roles) should be inside a properties file. There no interface to change this behaviour

**Comment by sberyozkin** [comment]
I've created https://issues.jboss.org/browse/THORN-2305.
@vepo, can you please watch it ?

**Comment by sberyozkin** [comment]
Hi @vepo, let me clarify one thing though, you mentioned " given the JWT token retrieves all user roles". 
Did you mean, retrieve the user roles from the token or use some token claim to help with the retrieval of the roles (from DB, etc) ? It has to be the latter, please clarify

**Comment by kenfinnigan** [comment]
Closing as JIRA has been created
