### ISSUE TITLE
Examples with Fractions

### ISSUE THREAD

**Issue by madduci** [thorntail/thorntail#1221]
Hi

I'm trying to work with custom fraction but I found it a little bit confusing and took me a couple of days to figure out everything.
I think a deeper chapter on Fractions would be helpful for the end user, maybe a Thorntail-Example would also help to kick-start the project.

It would be also helpful to see the interaction with other fractions (e.g. configuring and accessing the data sources, keystores, realms or similar).

I still didn't figure out yet how to interact with the database that I've set with my Fraction via the DataSourceFraction, as long as the drivers are only available at a later stage.

**Comment by Ladicek** [comment]
This is about Thorntail v2 and hence belongs to JIRA: https://issues.jboss.org/projects/THORN
