### ISSUE TITLE
thorntail-runner doesn't work behind a proxy

### ISSUE THREAD

**Issue by rapnagw** [thorntail/thorntail#1222]
**Describe the bug**
Timeout exception

**To Reproduce**
1. Run `org.wildfly.swarm.runner.Runner` with a custom `-Dthorntail.runner.repositories` and no other access to the internet.
2. Wait ~20min
3. See error

**Expected behavior**
All request go through the Maven proxy repository defined on `thorntail.runner.repositories` instead of `https://repository.jboss.org/nexus/content/groups/public/` and `https://repo.maven.apache.org/maven2/`

**Desktop (please complete the following information):**
 - OS: Windows
- Thorntail-Runner: 2.3.0.Final

**Stacktrace(s)**
[Stacktrace](https://gist.github.com/rapnagw/b0000a83f71406ea8e07409cbe0e3fd1)

**Comment by Ladicek** [comment]
One, this is about Thorntail v2 and hence belongs to JIRA: https://issues.jboss.org/browse/THORN

Two, the `thorntail.runner.repositories` system property defines a set of _additional_ repositories, in addition to the built-in set of repositories. If you define repository mirrors in your `settings.xml` (per https://maven.apache.org/guides/mini/guide-mirror-settings.html), the `Runner` should respect those settings and use the mirrors.

**Comment by rapnagw** [comment]
Thanks for clarification. Link for tractability https://issues.jboss.org/browse/THORN-2278

By the way, in my setup thorntail-runner didn't respect any settings from `settings.xml`.  From reading the comments on https://issues.jboss.org/browse/THORN-2224 I found this statement from Michał Szynkiewicz:

> Runner is build-system agnostic, it doesn't know anything about maven settings.

**Comment by Ladicek** [comment]
Hmm, the `MavenInitializer` class certainly looks like it loads `settings.xml`, but perhaps I got that wrong.
