### ISSUE TITLE
Unit test failing due to NoClassDefFoundError

### ISSUE THREAD

**Issue by agentS** [thorntail/thorntail#1229]
**Describe the bug**
Every test that involves classes defined in a different package than the test is defined in fails due to a `NoClassDefFoundError` when loading the classes defined outside the package the test is defined in.

**To Reproduce**
1. Define an Arquillian test
2. Define a class outside the Arquillian test's package
3. Create a new instance of the class from the Arquillian test
4. A `java.lang.NoClassDefFoundError` exception is thrown

**Expected behavior**
The test should run as expected and either fail or pass.

**Desktop:**
 - OS: Linux Mint 19.1
 - Version 2.3.0.Final

**Stacktrace**
[Exception](https://gist.github.com/agentS/09376959967081552a318efe1bf217d3)

**Additional context**
- [Code of the Arquillian test](https://gist.github.com/agentS/5cadd348cc04a64e7203d073b445aaa4)
- [Code of the fixture](https://gist.github.com/agentS/9a5a4c84717ed0f8d454ab728967bf4d)
- [Code of the weather station class](https://gist.github.com/agentS/001c7e77413e7d02435ca6d1c7470813)
- [Code of the DAO factory interface](https://gist.github.com/agentS/c030977fdb14b38ac2d40b1c7bc37144)
- [Code of the PostgreSQL DAO factory](https://gist.github.com/agentS/d4750bd4231baf85c95eb985733565c3)

**Comment by kenfinnigan** [comment]
As this relates to v2, could you create an issue in JIRA: https://issues.jboss.org/browse/THORN

**Comment by Ladicek** [comment]
The test uses `@DefaultDeployment`, so this is actually by design. We can discuss if this design is wrong, but currently, this is the intended behavior. You can construct your own `@Deployment` manually, and you have full control over which classes and resources are included.

**Comment by agentS** [comment]
Okay, I'll try to create my own `@Deployment`. It would be nice if you could include creating an own `@Deployment` in the guide.
