### ISSUE TITLE
documentation bug: thorntail.web-services.* should be thorntail.webservice.*

### ISSUE THREAD

**Issue by NiasSt90** [thorntail/thorntail#1261]
**Describe the bug**
all property-keys for webservice subsystem configuration are wrong:
instead of: 
`thorntail.web-services.wsdl-host` it should be 
`thorntail.webservices.wsdl-host` and so on...

**Comment by Ladicek** [comment]
This is about Thorntail 2 and hence belongs to JIRA: https://issues.jboss.org/browse/THORN

**Comment by Ladicek** [comment]
Filed https://issues.jboss.org/browse/THORN-2373
