### ISSUE TITLE
Microprofile Opentracing & Fault Tolerance Strange behavior

### ISSUE THREAD

**Issue by agonzalezl** [thorntail/thorntail#1272]
**Describe the bug**
I have 3 microservices with microporfile 2.1 opentracing, Rest Client and Fault tolerance. I redirect all traces to a Jaeger server. The following code works fine

```
MsBInterface msBResource = RestClientBuilder.newBuilder()
	            .baseUri(URI.create(urlA))
	            .register(new SmallRyeClientTracingFeature(tracer))
	            .build(MsBInterface.class);
		
	
	
RestaurantInterface restaurantResource = RestClientBuilder.newBuilder()
	            .baseUri(URI.create(buidlURL("msA")))
	            .register(new SmallRyeClientTracingFeature(tracer))
	            .build(RestaurantInterface.class);


    @GET
    @Path("/resilience")
    @Produces(MediaType.TEXT_PLAIN) 
    public String resilience() {
    	
        Set<Restaurant> restaurants =  restaurantResource.getAll();    	

	for(Restaurant restaurant : restaurants) {
		msBResource.resilience(restaurant);
	}
			
        return "OK";
}
```
With this expected behavior in Jaeger

![image](https://user-images.githubusercontent.com/18404667/55982432-30ccf180-5c99-11e9-9ba9-aec7de29c94a.png)

But when you try to use the Timeout tag in the method

```
    @GET
    @Fallback(fallbackMethod = "fallback") 
    @Timeout(5000000)
    @Path("/resilience")
    @Produces(MediaType.TEXT_PLAIN)
    public String resilience() {
```
It splits the traces (the timeout do no ocurred)
![image](https://user-images.githubusercontent.com/18404667/55982826-0b8cb300-5c9a-11e9-8f49-a0883bf51919.png)

I am not sure if this a Fault Tolerance error or a Opentracing error.

My pom dependencies
```
    <dependency>
      <groupId>org.eclipse.microprofile</groupId>
      <artifactId>microprofile</artifactId>
      <version>2.1</version>
      <type>pom</type>
      <scope>provided</scope>
    </dependency>
    
    <dependency>
	    <groupId>io.thorntail</groupId>
	    <artifactId>microprofile-opentracing</artifactId>
	</dependency>
	
	<dependency>
	    <groupId>io.thorntail</groupId>
	    <artifactId>microprofile-fault-tolerance</artifactId>
	</dependency>
	
	<dependency>
	    <groupId>io.thorntail</groupId>
	    <artifactId>jaeger</artifactId>
	</dependency>
```

**Comment by Ladicek** [comment]
This is a Thorntail v2 issue and hence belong to JIRA: https://issues.jboss.org/browse/THORN

I didn't try it, but our implementation of `@Timeout` delegates to an extra thread, so trace propagation might not work well in such case.

**Comment by Ladicek** [comment]
Thanks for filing https://issues.jboss.org/browse/THORN-2387, closing this one.
