### ISSUE TITLE
org.wildfly.swam.mail pulls in asm-6.0 jar.

### ISSUE THREAD

**Issue by karlnicholas** [thorntail/thorntail#929]
I'm just starting to try to get this project to work as uberjar, so bear with me. I'm trying to use the build plugin and it didn't seem to be detecting the javax.mail api I am using, so I included org.wildfly.swam.mail in the pom.xml to tell it to add the fraction. However, the application stopped working under plain wildfly-10.1 (and I think it would be the same under 11.0) because adding the compile dependency for mail in the pom brought in asm-6.0.jar and that messed up the application startup. This for version 2018.5.0.

**Comment by kg6zvp** [comment]
To clarify, are you trying to essentially use swarm as a second build target? ie: war for plain Wildfly, uberjar for "standalone" operation?

**Comment by Ladicek** [comment]
One, this seems to be an issue with WildFly Swarm / Thorntail 2.x, and that belongs to JBoss.org JIRA.

Two, the `mail` fraction does have autodetection support, so if that doesn't work for you, it sounds like a bug. Could you share more details?

And three, adding the `mail` fraction in a dedicated Maven profile should do the trick for you.

**Comment by karlnicholas** [comment]
Hi, to clarify, yes, it builds a war which runs on plain wildfly. I added the swarm plugin to get the uberjar as well and run it standalone. Seems okay to do with simpler projects, a rest only .war and uberjar for example. I don't use at the moment profiles but could add them though I don't think it will make much difference. There seems to be two .wars and the final uberjar when the build is done, but yea, a profile will probably be useful when I get further along.

**Comment by karlnicholas** [comment]
One: Okay, can look there, but do you think it's a problem Wildfly should address if I'm adding asm-6.0 into my project? Won't they just tell me not to do that?

Two: Yea, I was wondering about auto-detection. I'll have to look closer. There's obviously dependencies in the project but I'm not sure about the state of the code at the moment. Basically it should be a scheduled process that wakes up and emails users from the database that need emails for registration. Also, the about/contact page should fire off a thread for emailing. 

Three: Sounds like a plan.

**Comment by karlnicholas** [comment]
One: Okay.
Three: Okay, also sounds like a plan.

I looked briefly at project re auto-detection. The EJB's are in a separate jar that is a dependency to the main project, so that might be confusing the auto-detect. I can try to reproduce if it's important, but it could be a jboss specific issue. The mail code is part of an `@Asynchronous` ejb bean. The javax.mail stuff starts by referencing a jndi service, e.g., 

	@Resource(mappedName = "java:jboss/mail/Default")
	private Session mailSession;

A tutorial for the same would be http://mastertheboss.com/jboss-server/jboss-configuration/jboss-mail-service-configuration

**Comment by kg6zvp** [comment]
@karlnicholas: @Ladicek gave some great advice. Depending on the complexity of your project, you've got two options:

1. Specify the mail fraction as a dependency in a maven profile for Thorntail (what I'm currently doing on one project targeting application servers and Thorntail as embedded)
1. Specify the mail fraction inside of the plugin configuration block, like so:

```xml
<plugin>
	<groupId>org.wildfly.swarm</groupId>
	<artifactId>wildfly-swarm-plugin</artifactId>
	<version>${version.wildfly.swarm}</version>
	<executions>
		<execution>
			<goals>
				<goal>package</goal>
			</goals>
			<configuration>
				<fractionDetectMode>force</fractionDetectMode> <!-- Allow other fractions to be auto-detected even though mail is specified -->
				<fractions>mail</fractions> <!-- add mail fraction. No need to include groupId as org.wildfly.swarm will be assumed -->
			</configuration>
		</execution>
	</executions>
</plugin>
```

Source: http://docs.wildfly-swarm.io/2018.5.0/#maven-plugin

**Comment by Ladicek** [comment]
@kg6zvp FYI, you don't really need `<fractionDetectMode>force</fractionDetectMode>` if you use `<fractions>mail</fractions>` in the Maven plugin configuration. The only situation in which you need to force autodetection is when you specifiy a _dependency_ on some fraction.

**Comment by Ladicek** [comment]
@karlnicholas Yea I think fraction autodetection doesn't look into dependencies.

**Comment by karlnicholas** [comment]
@Ladicek - well, having the ejb's in a separate jar doesn't seem to be causing trouble because many other fractions are found. It may be related to what classes are searched for. Using a resource seems to be the recommended way to use the javax.mail api in wildfly.

    @Resource(mappedName = "java:jboss/mail/Default")
    private Session mailSession;
    MimeMessage m = new MimeMessage(mailSession);

**Comment by Ladicek** [comment]
@karlnicholas OK, I don't know then. If I recall, the `Session` type comes from `javax.mail`, so it should get autodetected; same with `MimeMessage`. Not sure why it doesn't.

**Comment by karlnicholas** [comment]
Right. I'll figure out a JIRA entry a little bit later and maybe see if I can track it down an make a PR. Thanks again.

**Comment by karlnicholas** [comment]
>> @karlnicholas Yea I think fraction autodetection doesn't look into dependencies.

Yea, playing around a little bit more I think you're right it's not looking at the separate ejb jar dependency. Lots of things are not being included, datasources and so on. I'll combine them for now and see how it goes. Thanks again.

**Comment by kenfinnigan** [comment]
Closing as not relevant to v4, please raise an issue at http://issues.jboss.org/browse/THORN for v2 issues
