### ISSUE TITLE
Docker plugin will not include the built JAR in the image

### ISSUE THREAD

**Issue by jesuino** [thorntail/thorntail#951]
Hi,

Looks like when we run docker:build the JAR with the app artifacts is not included in the image. Please see this project: https://github.com/jesuino/java-ml-projects/tree/748db8648eeb8ff39b39191b4a01d2bf89e18788

When I build the image I see the content but I can't find image-classifier-microservice,jar in the image directory (I use docker exec to check the image content), hence the image is working perfectly (great plugin, thanks), but my app is not starting.

Checking runt.sh I found the following:
~~~
APP_DIR=$ROOT_DIR/app
APP_CP=$APP_DIR/*.jar
~~~
Hence I think that a workaround is copy my JAR to target/image-classifier-microservice-bin/app and it works. Hence why I am not opening this on the fabric8 plugin. 

Please let me know if I am missing something! I am sorry in advanced if I am doing something n00b 0_0

**Comment by bobmcwhirter** [comment]
It’s the mode=thin causing that. It intentionally excludes the app artifact
from the staging dir layout.

If you remove that then your jar will appear in the app directory. In
theory.

**Comment by jesuino** [comment]
Thanks, that made it! I knew I was missing something ^_^
