### ISSUE TITLE
ActiveInstance does not support interceptors/decorators and does not destoy @Dependent dependencies correctly

### ISSUE THREAD

**Issue by mkouba** [thorntail/thorntail#994]
`io.thorntail.ActiveInstance` does not support interceptors/decorators as stated in `io.thorntail.Thorntail.activate()` javadoc. In fact, if you try to "activate" an instance of a class that should be decorated, you'll get `java.lang.ClassCastException`.

I'm not aware of any way how to support decorators ATM. For interceptors we could probably reuse the code we have for [CDI 2.0 `InterceptionFactory`](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#interception_factory). However, I'm not sure it is worth the effort.

Furhtermore,  `ActiveInstance` does not destroy `@Dependent` dependencies correctly because `CreationalContext.release()` is not called.

**Comment by bobmcwhirter** [comment]
So this isn't doing what I'd hoped?

https://github.com/thorntail/thorntail/blob/4.x/core/kernel/src/main/java/io/thorntail/ActiveInstance.java#L42-L48

I may have discovered that, but then worked around without decorators.  I don't actually recall.

**Comment by mkouba** [comment]
@bobmcwhirter Nope. I have a fix for interceptors. I don't think decorators are that important.

**Comment by kenfinnigan** [comment]
Resolved via #995
